### ISSUE TITLE
helpers.php - different location between readme and index.php script

### ISSUE THREAD

**Issue by seb-legat** [hananils/kirby-missing-link#1]
Hello,
Nice way to organize custom functions without using plugins ;)
But there's an error between the readme and the index.php concerning helpers.php usage.
In the readme: "You can also create a helpers.php file inside the methods folder".
But in your index.php file: F::loadOnce(kirby()->root('site') . '/helpers.php');
So helpers.php should be at the root of the "site" folder, not in the "methods" folder or it will not be loaded by your plugin.

**Comment by nilshoerrmann** [comment]
Good catch – thanks for notifying us!

**Comment by jaro-io** [comment]
@nilshoerrmann will you maybe find a minute to update this? would be super helpful! 🙏🏻 ✨

**Comment by nilshoerrmann** [comment]
Version 2.0.0 should finally fix the docs:
https://github.com/hananils/kirby-methods-folder/releases/tag/2.0.0
