### ISSUE TITLE
Support block methods

### ISSUE THREAD

**Issue by jonasfeige** [hananils/kirby-missing-link#2]
Hi guys.

Could you add support for [block methods](https://getkirby.com/docs/reference/plugins/extensions/block-methods)? It's pretty straight forward and I've patched it myself, but would of course be cleaner if the plugin handled this in the first place.

[Layout column](https://getkirby.com/docs/reference/plugins/extensions/layout-column-methods) and [Layout methods](https://getkirby.com/docs/reference/plugins/extensions/layout-methods) would also be much appreciated. :)

Really love this plugin by the way, use it on every Kirby install.

**Comment by nilshoerrmann** [comment]
Block and layout methods are now included in version 2.0.0.
